[package]
name = "ordsearch"
version = "0.2.3"

description = "A data structure for efficient lower-bound lookups"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/ordsearch"
homepage = "https://github.com/jonhoo/ordsearch"
repository = "https://github.com/jonhoo/ordsearch.git"

keywords = ["data-structures", "search", "performance", "Eytzinger"]
categories = ["data-structures", "memory-management"]

license = "MIT/Apache-2.0"

[features]
default = []
nightly = []

[badges]
travis-ci = { repository = "jonhoo/ordsearch" }
maintenance = { status = "as-is" }

[dependencies]
rand = "0.8.5"
rust-pairwise-testing = { path = "/Users/bazhenov/Developer/rust-pairwise-testing" }
