name: Benchmarks

permissions:
  contents: read

on:
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          path: baseline-branch

      - name: Prepare Environment
        run: |
          rustup update stable
          rustup default stable
          cargo install cargo-export --version 0.2.0

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
            ./baseline-branch/target/
          key: Bench/${{ runner.os }}

      - name: Building Benchmarks
        run: |
          cargo export target/benchmarks -- bench --bench=search_ord
          cd baseline-branch
          cargo export target/benchmarks -- bench --bench=search_ord

      - name: Run Benchmarks
        run: |
          set -eo pipefail

          target/benchmarks/search_ord --color=never compare baseline-branch/target/benchmarks/search_ord \
            -v -o -t 1 --fail-threshold 10 | tee target/benchmark.txt

      - uses: actions/upload-artifact@v3
        with:
          name: benchmark.txt
          path: target/benchmark.txt
